[build]
  command = "cd \"Speech Practice Web App\" && npm install && npm run build"
  publish = "Speech Practice Web App/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
